user_login:
  username: your_username
  password: your_password
  pin: your_pin
base_url: https://your-oscar-url.com
last_processed_pdf: ''
last_pending_doc_file: ''
enable_ocr_gpu: false
workflow_file: workflow.csv
