base_url: "http://localhost:8080/oscar"
user_login:
  username: "oscardoc"
  password: ""
  pin: "1117"
last_processed_pdf: ""
enable_ocr_gpu: true
last_pending_doc_file: ''
urls:
  login: /login.do
chrome_options:
  headless: true
ai_config:
  url: "http://127.0.0.1:5000/v1/chat/completions"
  auth_token: "qwerty"
  temperature: 0.1
  top_p: 0.1
logging:
  version: 1
  disable_existing_loggers: false
  formatters:
    standard:
      format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  handlers:
    console:
      class: logging.StreamHandler
      level: DEBUG
      formatter: standard
      stream: ext://sys.stdout
    file:
      class: logging.FileHandler
      level: INFO
      formatter: standard
      filename: oscar_automation.log
  root:
    level: INFO
    handlers: [console, file]
  filename: log_test_28_emr_test.txt

