base_url: "http://localhost:8080/oscar"
user_login:
  username: "oscardoc"
  password: ""
  pin: "1117"
last_processed_pdf: ""
enable_ocr_gpu: true
last_pending_doc_file: ''
urls:
  login: /login.do
chrome_options:
  headless: true
ai_config:
  url: "http://127.0.0.1:5000/v1/chat/completions"
  auth_token: "qwerty"
  temperature: 0.1
  top_p: 0.1
logging:
  version: 1
  disable_existing_loggers: false
  formatters:
    standard:
      format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  handlers:
    console:
      class: logging.StreamHandler
      level: DEBUG
      formatter: standard
      stream: ext://sys.stdout
    file:
      class: logging.FileHandler
      level: INFO
      formatter: standard
      filename: oscar_automation.log
  root:
    level: INFO
    handlers: [ console, file ]
  filename: log_test_28_emr_test.txt
workflow:
  steps:
    - name: has_ocr
    - name: extract_text_from_pdf
    - name: extract_text_from_pdf_file
    - name: extract_text_doctr
    - name: build_prompt
    - name: get_document_description
    - name: getProviderList
    - name: get_patient_name
    - name: set_patient
    - name: set_doctor
    - name: oscar_update
document_categories:
  - Lab
  - Consult
  - Insurance
  - Legal
  - Old Chart
  - Radiology
  - Pathology
  - Others
  - Photo
  - Consent
  - Diagnostics
  - Pharmacy
  - Requisition
  - Referral
  - Request
  - Advertisement
huey:
  name: workflow_queue
  results: True
  store_none: False
  always_eager: False
  connection:
    host: localhost
    port: 6379
emr:
  base_url: 'http://localhost:8080/oscar'
  username: 'admin'
  password: 'admin'
ocr:
  enable_gpu: False
  tesseract_path: '/usr/bin/tesseract'
file_processing:
  input_directory: '/path/to/input/files'
  output_directory: '/path/to/output/files'
  allowed_extensions: [ '.pdf', '.jpg', '.png', '.tiff' ]

